#!/usr/bin/env bash
# Install nginx and and make it return a page with a string 'Holberton School'

apt-get -y install nginx
echo "Holberton School" > /etc/nginx/html/index.htmlecho
service nginx start
