#!/usr/bin/env bash
# Install nginx and and make it return a page with a string 'Holberton School'

apt-get update
apt-get -y install nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Holberton School" > /etc/nginx/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx start
