#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sed  -i '6i location /redirect_me { return  301 Moved Permanently https://www.youtube.com/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default

service nginx restart
